import asyncio
import os
import sys

# Ensure backend directory is in path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from motor.motor_asyncio import AsyncIOMotorClient
from app.config import settings

# Core sample properties matching your mockData.ts
SAMPLE_PROPERTIES = [
    {
        "property_id": "prop-001",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Spacious 3BHK in Kondapur",
        "locality": "Kondapur",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 3,
        "area_sqft": 1650,
        "price": 8500000,
        "price_per_sqft": 5151,
        "furnishing": "SEMI",
        "age_years": 4,
        "amenity_count": 8,
        "verified": True,
        "latitude": 17.4590,
        "longitude": 78.3534,
        "description": "Premium 3BHK with excellent connectivity to HITEC City. Clubhouse, gym, and swimming pool.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-002",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "2BHK Apartment in Gachibowli",
        "locality": "Gachibowli",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 2,
        "area_sqft": 1100,
        "price": 5500000,
        "price_per_sqft": 5000,
        "furnishing": "FURNISHED",
        "age_years": 2,
        "amenity_count": 6,
        "verified": True,
        "latitude": 17.4401,
        "longitude": 78.3489,
        "description": "Fully furnished 2BHK near financial district. Modern amenities, 24/7 security.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-003",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "4BHK Villa in Jubilee Hills",
        "locality": "Jubilee Hills",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 4,
        "area_sqft": 3200,
        "price": 25000000,
        "price_per_sqft": 7812,
        "furnishing": "FURNISHED",
        "age_years": 1,
        "amenity_count": 12,
        "verified": True,
        "latitude": 17.4256,
        "longitude": 78.4096,
        "description": "Luxurious 4BHK villa with private garden in Jubilee Hills. Best schools and hospitals nearby.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-004",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Commercial Office Space HITEC City",
        "locality": "HITEC City",
        "city": "Hyderabad",
        "listing_type": "COMMERCIAL",
        "bhk": 0,
        "area_sqft": 5000,
        "price": 45000000,
        "price_per_sqft": 9000,
        "furnishing": "SEMI",
        "age_years": 3,
        "amenity_count": 10,
        "verified": True,
        "latitude": 17.4477,
        "longitude": 78.3763,
        "description": "Grade-A commercial office space in HITEC City. Ideal for IT companies. Ample parking.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-005",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Premium Plot in Shadnagar",
        "locality": "Shadnagar",
        "city": "Hyderabad",
        "listing_type": "LAND",
        "bhk": 0,
        "area_sqft": 2400,
        "price": 3500000,
        "price_per_sqft": 1458,
        "furnishing": "UNFURNISHED",
        "age_years": 0,
        "amenity_count": 0,
        "verified": True,
        "latitude": 17.0701,
        "longitude": 78.2045,
        "description": "Clear title DTCP approved plot in fast-growing Shadnagar area.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-006",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Luxury 5BHK Penthouse Banjara Hills",
        "locality": "Banjara Hills",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 5,
        "area_sqft": 4500,
        "price": 65000000,
        "price_per_sqft": 14444,
        "furnishing": "FULLY_FURNISHED",
        "age_years": 1,
        "amenity_count": 15,
        "verified": True,
        "latitude": 17.4108,
        "longitude": 78.4483,
        "description": "Stunning city views from this top-floor penthouse. Private pool included.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-007",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "3BHK Flat near Metro",
        "locality": "KPHB",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 3,
        "area_sqft": 1550,
        "price": 8200000,
        "price_per_sqft": 5290,
        "furnishing": "SEMI",
        "age_years": 2,
        "amenity_count": 6,
        "verified": True,
        "latitude": 17.4932,
        "longitude": 78.3941,
        "description": "Just 2 mins walk to KPHB Metro Station. High rental yield area.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-008",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Commercial Shop on Main Road",
        "locality": "Madhapur",
        "city": "Hyderabad",
        "listing_type": "COMMERCIAL",
        "bhk": 0,
        "area_sqft": 850,
        "price": 12500000,
        "price_per_sqft": 14705,
        "furnishing": "UNFURNISHED",
        "age_years": 5,
        "amenity_count": 2,
        "verified": True,
        "latitude": 17.4504,
        "longitude": 78.3908,
        "description": "High footfall commercial shop in Madhapur main road. Ideal for retail or food outlet.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-009",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "HMDA Approved Plot",
        "locality": "Miyapur",
        "city": "Hyderabad",
        "listing_type": "LAND",
        "bhk": 0,
        "area_sqft": 3600,
        "price": 6500000,
        "price_per_sqft": 1805,
        "furnishing": "UNFURNISHED",
        "age_years": 0,
        "amenity_count": 0,
        "verified": True,
        "latitude": 17.4961,
        "longitude": 78.3390,
        "description": "Corner plot with clear title in a rapidly developing sector of Miyapur.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-010",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "2BHK Budget Friendly",
        "locality": "Uppal",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 2,
        "area_sqft": 1050,
        "price": 4200000,
        "price_per_sqft": 4000,
        "furnishing": "UNFURNISHED",
        "age_years": 8,
        "amenity_count": 3,
        "verified": True,
        "latitude": 17.4017,
        "longitude": 78.5601,
        "description": "Affordable 2BHK in a peaceful residential colony in Uppal.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-011",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Luxury 4BHK Independent House",
        "locality": "Manikonda",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 4,
        "area_sqft": 2800,
        "price": 18000000,
        "price_per_sqft": 6428,
        "furnishing": "FURNISHED",
        "age_years": 3,
        "amenity_count": 8,
        "verified": True,
        "latitude": 17.3988,
        "longitude": 78.3891,
        "description": "Spacious independent house with modern interiors, car parking, and terrace garden.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-012",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "IT Park Office Space",
        "locality": "Gachibowli",
        "city": "Hyderabad",
        "listing_type": "COMMERCIAL",
        "bhk": 0,
        "area_sqft": 10000,
        "price": 95000000,
        "price_per_sqft": 9500,
        "furnishing": "FURNISHED",
        "age_years": 2,
        "amenity_count": 14,
        "verified": True,
        "latitude": 17.4410,
        "longitude": 78.3470,
        "description": "Plug and play office space suitable for IT/ITES companies. Central AC, 100% backup.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-013",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Cozy 1BHK Studio",
        "locality": "Kondapur",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 1,
        "area_sqft": 600,
        "price": 3500000,
        "price_per_sqft": 5833,
        "furnishing": "FULLY_FURNISHED",
        "age_years": 1,
        "amenity_count": 4,
        "verified": True,
        "latitude": 17.4600,
        "longitude": 78.3550,
        "description": "Perfect bachelor pad or investment property. Walkable to major tech parks.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-014",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Agricultural Land",
        "locality": "Moinabad",
        "city": "Hyderabad",
        "listing_type": "LAND",
        "bhk": 0,
        "area_sqft": 10890,
        "price": 15000000,
        "price_per_sqft": 1377,
        "furnishing": "UNFURNISHED",
        "age_years": 0,
        "amenity_count": 0,
        "verified": False,
        "latitude": 17.3275,
        "longitude": 78.2741,
        "description": "Quarter acre agricultural land, good potential for future farmhouse development.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-015",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "3BHK Premium Apartment",
        "locality": "Banjara Hills",
        "city": "Hyderabad",
        "listing_type": "RESIDENTIAL",
        "bhk": 3,
        "area_sqft": 2200,
        "price": 21000000,
        "price_per_sqft": 9545,
        "furnishing": "SEMI",
        "age_years": 5,
        "amenity_count": 10,
        "verified": True,
        "latitude": 17.4150,
        "longitude": 78.4347,
        "description": "Spacious 3BHK in Road No. 12, Banjara Hills. High-end society with club class amenities.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-016",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Retail Space in Mall",
        "locality": "Secunderabad",
        "city": "Hyderabad",
        "listing_type": "COMMERCIAL",
        "bhk": 0,
        "area_sqft": 1200,
        "price": 14000000,
        "price_per_sqft": 11666,
        "furnishing": "UNFURNISHED",
        "age_years": 2,
        "amenity_count": 5,
        "verified": True,
        "latitude": 17.4399,
        "longitude": 78.4983,
        "description": "Ground floor retail space inside a popular mall in Secunderabad.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-017",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Residential Plot in Tellapur",
        "locality": "Tellapur",
        "city": "Hyderabad",
        "listing_type": "LAND",
        "land_use_zone": "RESIDENTIAL",
        "bhk": 0,
        "area_sqft": 2400,
        "price": 9800000,
        "price_per_sqft": 4083,
        "furnishing": "UNFURNISHED",
        "age_years": 0,
        "amenity_count": 3,
        "verified": True,
        "latitude": 17.4715,
        "longitude": 78.2948,
        "description": "HMDA-approved residential plot in Tellapur with 40 ft road access, clear title, and gated layout development nearby.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-018",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Residential Plot in Shadnagar",
        "locality": "Shadnagar",
        "city": "Hyderabad",
        "listing_type": "LAND",
        "land_use_zone": "RESIDENTIAL",
        "bhk": 0,
        "area_sqft": 2400,
        "price": 4200000,
        "price_per_sqft": 1750,
        "furnishing": "UNFURNISHED",
        "age_years": 0,
        "amenity_count": 3,
        "verified": True,
        "latitude": 17.0701,
        "longitude": 78.2045,
        "description": "DTCP-approved residential plot near Shadnagar growth corridor, suitable for independent house construction or long-term investment.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-019",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Commercial Plot in Financial District",
        "locality": "Financial District",
        "city": "Hyderabad",
        "listing_type": "COMMERCIAL",
        "land_use_zone": "COMMERCIAL",
        "bhk": 0,
        "area_sqft": 4800,
        "price": 65000000,
        "price_per_sqft": 13542,
        "furnishing": "UNFURNISHED",
        "age_years": 0,
        "amenity_count": 3,
        "verified": True,
        "latitude": 17.4227,
        "longitude": 78.3446,
        "description": "Prime commercial plot near Financial District with wide road frontage, high FSI potential, and strong office redevelopment demand.",
        "status": "ACTIVE"
    },
    {
        "property_id": "prop-020",
        "owner_user_id": "mock-seller-id",
        "seller_id": "mock-seller-id",
        "title": "Commercial Plot in Kompally",
        "locality": "Kompally",
        "city": "Hyderabad",
        "listing_type": "COMMERCIAL",
        "land_use_zone": "COMMERCIAL",
        "bhk": 0,
        "area_sqft": 3600,
        "price": 28500000,
        "price_per_sqft": 7917,
        "furnishing": "UNFURNISHED",
        "age_years": 0,
        "amenity_count": 3,
        "verified": True,
        "latitude": 17.5433,
        "longitude": 78.4788,
        "description": "Road-facing commercial plot in Kompally, suitable for showroom, clinic, retail outlet, or mixed-use development.",
        "status": "ACTIVE"
    }
]

async def seed_database():
    print(f"Connecting to MongoDB Atlas...")
    client = AsyncIOMotorClient(settings.MONGODB_URI)
    db = client[settings.MONGODB_DB_NAME]
    collection = db["properties"]
    
    print("Clearing old mock properties...")
    await collection.delete_many({"property_id": {"$regex": "^prop-"}})
    
    print(f"Inserting {len(SAMPLE_PROPERTIES)} sample properties into Atlas...")
    await collection.insert_many(SAMPLE_PROPERTIES)
    print("✅ Successfully seeded MongoDB Atlas!")

if __name__ == "__main__":
    asyncio.run(seed_database())
